// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snbcrmztumgffrmandyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYmNybXp0dW1nZmZybWFuZHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODAyNTgsImV4cCI6MjA2ODE1NjI1OH0.Qxobz3cM_lgQmaLkreBNltd189fFywRiIsdUzzoEGpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});